### ISSUE TITLE
Impossible to download playlists

### ISSUE THREAD

**Issue by christubuntu** [sourabhkv/ytdl#3]
I click on Download and nothing happens

**Comment by sourabhkv** [comment]
Which version are you using? also send the link used

**Comment by sourabhkv** [comment]
just realised there was small bug , this is fixed in [latest release](https://github.com/sourabhkv/ytdl/releases/tag/v22.0514.22)

**Comment by christubuntu** [comment]
Updated to that version, still the issue is not resolved. I'm trying to download this playlist (https://www.youtube.com/playlist?list=PL82FJ-neEjQ0r8oqZdLxKa7vycC53u7GS) and this is what's happening. Notice it immediately says Download complete.

https://user-images.githubusercontent.com/55885756/168467269-6daca5e2-c31e-4d40-94ce-89d71135f8d4.mp4

**Comment by sourabhkv** [comment]
Use version 22.0514.22 do not update from older version as backend gets updated not full application
Uninstall application and reinstall [this](https://github.com/sourabhkv/ytdl/releases/download/v22.0514.22/Youtube-dl.GUI.Portable.zip)

[here](https://user-images.githubusercontent.com/55890376/168638995-183ba08b-91ac-4a72-a6c1-bf152d71c0ea.mp4) is playlist downloading in action

**Comment by christubuntu** [comment]
Fixed
